const cardFiles=['01_karginyai.png','02_skorpibum.png','03_gunbary.png','04_zubastyi_orm.png','05_bindigar.png','06_kortodeya.png','07_barbidu.png','08_kulka_pechushka.png','09_grustik_holi_liukh.png','10_chutzik.png','11_megaremza.png','12_mindibulka.png','13_zlisum.png','14_bezzruchka.png','15_krivulka_khodulka.png','16_veselmak.png','17_vulkopuk.png','18_pshigvipum.png','19_kakturem.png'];
const spriteNames=['Каргиняй','Скорпибум','Гунбары','Зубастый Орм','Биндигар','Кортодея','Барбиду','Кулька-Печушка','Грустик Холи-Лиух','Чутзик','Мегарэмза','Миндибулька','Злисун','Беззручка','Кривулька-ходулька','Весельмак','Вулкопук','Пшигвипум','КактуРем'];
const normalIds=[0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17];
const colors=['#7657d6','#ff6fae','#24a979','#f39b35']; const avatarPool=[0,1,2,3,4,5]; let avatarSelections=[0,3,5,1],config={count:2,rule:'classic',solo:false},players=[],deck=[],open=[],locked=false,current=0,found=0,sound=true,megaLeft=0,aiMemory=new Map(),soloStarted=0,soloInterval=null,musicOn=localStorage.getItem('mmMusicOn')!=='false',musicVolume=Number(localStorage.getItem('mmMusicVolume')??28)/100,sfxVolume=Number(localStorage.getItem('mmSfxVolume')??65)/100;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function spriteStyle(id){id=(Number(id)||0)%6;return `--ax:${(id%3)*50}%;--ay:${Math.floor(id/3)*100}%`}
function cardSrc(id){return `image/${cardFiles[id]}`}
function setupPlayers(){let host=$('#playerSetup'),defaultNames=['Матвей','Диана','Маша','Саша'];host.innerHTML='';for(let i=0;i<config.count;i++){let choices=avatarPool.map(id=>`<button class="avatar-choice ${avatarSelections[i]===id?'selected':''}" onclick="selectAvatar(${i},${id})" aria-label="Выбрать аватар"><span class="sprite" style="${spriteStyle(id)}"></span></button>`).join('');host.innerHTML+=`<div class="player-row" style="--accent:${colors[i]}"><div class="avatar"><div class="sprite" style="${spriteStyle(avatarSelections[i])}"></div></div><input maxlength="14" value="${defaultNames[i]}" aria-label="Имя игрока ${i+1}"><div class="avatar-options">${choices}</div></div>`}if(config.count===1&&!config.solo)host.innerHTML+=`<div class="player-row" style="--accent:${colors[1]}"><div class="avatar"><div class="sprite" style="${spriteStyle(2)}"></div></div><input value="Компик" disabled></div>`}
function selectAvatar(playerIndex,id){let names=$$('#playerSetup input:not([disabled])').map(x=>x.value);avatarSelections[playerIndex]=id;setupPlayers();$$('#playerSetup input:not([disabled])').forEach((x,i)=>x.value=names[i]||x.value)}
setupPlayers();
$$('.mode').forEach(b=>b.onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#soloBtn').classList.remove('selected');config.solo=false;config.count=+b.dataset.players;setupPlayers()});
$('#soloBtn').onclick=()=>{$$('.mode').forEach(x=>x.classList.remove('selected'));$('#soloBtn').classList.add('selected');config.solo=true;config.count=1;setupPlayers()};
$$('.rule').forEach(b=>b.onclick=()=>{$$('.rule').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');config.rule=b.dataset.rule});
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function start(){let names=$$('#playerSetup input').map(x=>x.value.trim()||'Игрок');players=names.map((name,i)=>({name,score:0,pairs:[],ai:!config.solo&&config.count===1&&i===1,avatar:!config.solo&&config.count===1&&i===1?2:avatarSelections[i],color:colors[i]}));deck=normalIds.flatMap(id=>[{kind:'normal',id},{kind:'normal',id}]);deck.push({kind:'mega',id:10},{kind:'kaktu',id:99});shuffle(deck);open=[];locked=false;current=0;found=0;megaLeft=0;aiMemory.clear();$('#specialSlots').innerHTML='<span data-label="Мегарэмза">М</span><span data-label="КактуРем">К</span>';showScreen('game');renderBoard();renderPlayers();startSoloTimer();updateStatus();startMusic();}
function startSoloTimer(){clearInterval(soloInterval);let timer=$('#soloTimer');timer.hidden=!config.solo;if(!config.solo)return;soloStarted=Date.now();let tick=()=>{let sec=Math.floor((Date.now()-soloStarted)/1000);timer.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};tick();soloInterval=setInterval(tick,250)}
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function renderBoard(){let b=$('#board');b.innerHTML='';deck.forEach((d,i)=>{let el=document.createElement('button');el.className=`card ${d.matched?'matched':''}`;el.dataset.i=i;el.setAttribute('aria-label','Закрытая карта');let imageId=d.kind==='kaktu'?18:d.id;el.innerHTML=`<span class="card-inner"><span class="face back"></span><span class="face front"><img class="card-image" src="${cardSrc(imageId)}" alt="${spriteNames[imageId]}"></span></span>`;el.onclick=()=>flip(i);b.append(el)})}
function renderPlayers(){let l=$('#playersLeft'),r=$('#playersRight');l.innerHTML='';r.innerHTML='';players.forEach((p,i)=>{let pile=p.pairs.map(id=>`<img class="pair-thumb" src="${cardSrc(id)}" alt="">`).join('');let html=`<div class="player-card ${i===current?'current':''}" data-player="${i}" style="--accent:${p.color}"><div class="avatar"><div class="sprite" style="${spriteStyle(p.avatar)}"></div></div><h3>${p.name}</h3><div class="score">${p.score}</div><div class="score-label">Собрано пар</div><div class="pair-pile">${pile}</div></div>`;(i%2?r:l).insertAdjacentHTML('beforeend',html)})}
function updateStatus(){let p=players[current];$('#turnText').textContent=`Ход: ${p.name}`;renderPlayers();if(p.ai&&!locked)setTimeout(aiTurn,700)}
function flip(i){if(locked)return;let c=$$('.card')[i],d=deck[i];if(c.classList.contains('flipped')||c.classList.contains('matched'))return;c.classList.add('flipped');c.setAttribute('aria-label',spriteNames[d.id]||'КактуРем');if(d.kind==='normal')aiMemory.set(i,d.id);tone(440,.05);if(d.kind!=='normal'){activateSpecial(i,d);return}open.push(i);if(megaLeft>0){megaLeft--;if(megaLeft===0){locked=true;setTimeout(finishMega,550)}return}if(open.length===2)checkPair()}
function flyImage(card,target,src,delay=0){setTimeout(()=>{let a=card.getBoundingClientRect(),b=target.getBoundingClientRect(),img=document.createElement('img');img.src=src;img.className='fly-card';img.style.cssText=`left:${a.left}px;top:${a.top}px;width:${a.width}px;height:${a.height}px`;document.body.append(img);requestAnimationFrame(()=>requestAnimationFrame(()=>{img.style.left=`${b.left+b.width/2-15}px`;img.style.top=`${b.top+b.height/2-19}px`;img.style.width='30px';img.style.height='38px';img.style.transform='rotate(360deg)'}));setTimeout(()=>img.remove(),780)},delay)}
function showPairInCenter(src,target,done){let stage=document.createElement('div');stage.className='pair-showcase';stage.innerHTML=`<div class="pair-burst">ПАРА!</div><img src="${src}"><img src="${src}">`;document.body.append(stage);requestAnimationFrame(()=>stage.classList.add('visible'));setTimeout(()=>{let end=target.getBoundingClientRect();stage.classList.add('leaving');[...stage.querySelectorAll('img')].forEach((img,n)=>{img.style.setProperty('--tx',`${end.left+end.width/2-(innerWidth/2)+(n?10:-10)}px`);img.style.setProperty('--ty',`${end.top+end.height/2-(innerHeight/2)}px`)})},1450);setTimeout(()=>{stage.remove();done()},2250)}
function checkPair(){locked=true;let [a,b]=open;if(deck[a].id===deck[b].id){let cards=$$('.card'),playerIndex=current,target=$(`.player-card[data-player="${playerIndex}"] .pair-pile`),src=cardSrc(deck[a].id);cards[a].classList.add('pair-origin');cards[b].classList.add('pair-origin');toast('Ура! Пара!');confetti();showPairInCenter(src,target,()=>{[a,b].forEach(i=>{deck[i].matched=true;cards[i].classList.remove('pair-origin');cards[i].classList.add('matched')});players[playerIndex].score++;players[playerIndex].pairs.push(deck[a].id);found++;open=[];locked=false;updateStatus();if(found===17)setTimeout(endGame,700);else if(config.rule==='classic')nextTurn()})}else setTimeout(()=>{$$('.card')[a].classList.remove('flipped');$$('.card')[b].classList.remove('flipped');open=[];locked=false;toast('Почти!');nextTurn()},1050)}
function nextTurn(){current=(current+1)%players.length;updateStatus()}
function activateSpecial(i,d){locked=true;open=[];let card=$$('.card')[i],imageId=d.kind==='kaktu'?18:10,slot=$$('#specialSlots span')[d.kind==='mega'?0:1];card.classList.add('special-celebrate');let finish=()=>{closeModal();flyImage(card,slot,cardSrc(imageId));d.matched=true;card.classList.remove('special-celebrate');card.classList.add('matched');setTimeout(()=>{slot.classList.add('filled');slot.innerHTML=`<img src="${cardSrc(imageId)}" alt="${spriteNames[imageId]}">`;if(d.kind==='mega'){megaLeft=3;locked=false;updateStatus()}else shuffleRemaining()},760)};setTimeout(()=>{if(d.kind==='mega')specialModal('МЕГАРЭМЗА!','Мегасила активирована!','Открой ещё 3 карточки','mega',finish);else specialModal('КАКТУРЕМ!','Он всё перепутал!','ПЕРЕМЕШАТЬ КАРТЫ','kaktu',finish)},750)}
function finishMega(){let cards=$$('.card'),revealed=[...open],groups={};revealed.forEach(i=>(groups[deck[i].id]??=[]).push(i));let pair=Object.values(groups).find(g=>g.length>1);if(pair){let [a,b]=pair,playerIndex=current,target=$(`.player-card[data-player="${playerIndex}"] .pair-pile`),src=cardSrc(deck[a].id);[a,b].forEach(i=>cards[i].classList.add('pair-origin'));toast('Мегапара! Ход продолжается!');confetti();showPairInCenter(src,target,()=>{[a,b].forEach(i=>{deck[i].matched=true;cards[i].classList.remove('pair-origin');cards[i].classList.add('matched')});revealed.filter(i=>i!==a&&i!==b).forEach(i=>cards[i].classList.remove('flipped'));players[playerIndex].score++;players[playerIndex].pairs.push(deck[a].id);found++;open=[];locked=false;updateStatus();if(found===17)setTimeout(endGame,700)})}else setTimeout(()=>{revealed.forEach(i=>cards[i].classList.remove('flipped'));open=[];locked=false;toast('В трёх картах пары нет');nextTurn()},850)}
function shuffleRemaining(){closeModal();aiMemory.clear();let cards=$$('.card'),idx=deck.map((d,i)=>i).filter(i=>!deck[i].matched);let vals=shuffle(idx.map(i=>deck[i]));idx.forEach((pos,k)=>deck[pos]=vals[k]);cards.forEach((c,i)=>{if(!c.classList.contains('matched')){c.style.setProperty('--sx',`${(2.5-i%6)*82}px`);c.style.setProperty('--sy',`${(2.5-Math.floor(i/6))*96}px`);c.style.setProperty('--rot',`${(i%2?1:-1)*(12+i%5*5)}deg`);c.style.setProperty('--i',i);c.classList.add('shuffle')}});setTimeout(()=>{renderBoard();locked=false;toast('Карты перемешаны!');updateStatus()},1150)}
function specialModal(title,sub,action,kind,cb){let imageId=kind==='kaktu'?18:10;$('#modalBody').innerHTML=`<div class="special-preview"><img class="card-image" src="${cardSrc(imageId)}" alt="${spriteNames[imageId]}"></div><h2 class="special-title">${title}</h2><h3>${sub}</h3><p>${action}</p><button id="specialAction" class="primary">${kind==='kaktu'?action:'ПРОДОЛЖИТЬ'}</button>`;openModal();$('#specialAction').onclick=cb}
function aiChoice(available){let known={};for(let i of available){let id=aiMemory.get(i);if(id!==undefined)(known[id]??=[]).push(i)}let pair=Object.values(known).find(v=>v.length>1);if(open.length===0&&pair)return pair[0];if(open.length===1){let wanted=deck[open[0]].id,match=(known[wanted]||[]).find(i=>i!==open[0]);if(match!==undefined)return match}let fresh=available.filter(i=>!aiMemory.has(i));return (fresh.length?fresh:available)[Math.floor(Math.random()*(fresh.length||available.length))]}
function aiTurn(){if(locked||!players[current]?.ai)return;let available=deck.map((_,i)=>i).filter(i=>!deck[i].matched&&!$$('.card')[i].classList.contains('flipped'));if(!available.length)return;flip(aiChoice(available));if(!locked&&open.length===1)setTimeout(aiTurn,700)}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1300)}
function confetti(){for(let i=0;i<18;i++){let x=document.createElement('i');x.className='confetti';x.style.cssText=`left:${45+Math.random()*10}%;top:40%;background:${colors[i%3]};--x:${(Math.random()-.5)*500}px`;$('#confetti').append(x);setTimeout(()=>x.remove(),1500)}}
function endGame(){locked=true;clearInterval(soloInterval);let max=Math.max(...players.map(p=>p.score)),w=players.filter(p=>p.score===max),elapsed=Math.floor((Date.now()-soloStarted)/1000),title=config.solo?`Готово за ${formatTime(elapsed)}!`:w.length>1?'Вот это битва! Ничья!':`Ура! ${w[0].name} победил${w[0].name.endsWith('а')?'а':''}!`;if(config.solo)saveSolo(w[0],elapsed);else saveWinner(w[0]);$('#modalBody').innerHTML=`<h2>${title}</h2><div class="avatar" style="width:100px;height:100px;margin:auto"><div class="sprite" style="${spriteStyle(w[0].avatar)}"></div></div><p style="text-align:center;font-size:22px">${max} ${max===1?'пара':'пар'}</p><button class="primary" onclick="start()">ЕЩЁ РАУНД</button><button class="text-btn" onclick="closeModal();showScreen('home')">В главное меню</button>`;openModal();confetti()}
function formatTime(sec){return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`}
function saveSolo(p,time){let a=JSON.parse(localStorage.getItem('mmSoloLeaders')||'[]');a.push({name:p.name,time,avatar:p.avatar});localStorage.setItem('mmSoloLeaders',JSON.stringify(a.sort((x,y)=>x.time-y.time).slice(0,10)))}
function saveWinner(p){let a=JSON.parse(localStorage.getItem('mmLeaders')||'[]'),x=a.find(v=>v.name===p.name);x?(x.wins++,x.points+=p.score):a.push({name:p.name,wins:1,points:p.score,avatar:p.avatar});localStorage.setItem('mmLeaders',JSON.stringify(a.sort((a,b)=>b.wins-a.wins||b.points-a.points).slice(0,10)))}
function openModal(){let m=$('#modal');m.classList.add('open');m.setAttribute('aria-hidden','false')}function closeModal(){let m=$('#modal');m.classList.remove('open');m.setAttribute('aria-hidden','true')}
function showInfo(type){if(type==='rules')$('#modalBody').innerHTML='<h2>Как играть?</h2><p>Открывай по две карты и ищи одинаковых монстриков. В соло найди все пары как можно быстрее!</p><ul><li><b>Мегарем</b> разрешит открыть ещё 3 карты.</li><li><b>КактуРем</b> перемешает закрытые карты.</li></ul>';else if(type==='soloLeaders'){let a=JSON.parse(localStorage.getItem('mmSoloLeaders')||'[]');$('#modalBody').innerHTML='<h2>⏱ Рекорды соло</h2>'+(a.length?a.slice(0,5).map((p,i)=>`<div class="leader"><b>${i+1}</b><div class="avatar"><div class="sprite" style="${spriteStyle(p.avatar)}"></div></div><span><b>${p.name}</b><br>${formatTime(p.time)}</span></div>`).join(''):'<p>Пока нет рекордов. Сыграй первым!</p>')}else{let a=JSON.parse(localStorage.getItem('mmLeaders')||'[]');$('#modalBody').innerHTML='<h2>🏆 Лучшие игроки</h2>'+(a.length?a.slice(0,3).map((p,i)=>`<div class="leader"><b>${i+1}</b><div class="avatar"><div class="sprite" style="${spriteStyle(p.avatar)}"></div></div><span><b>${p.name}</b><br>${p.wins} побед · ${p.points} очков</span></div>`).join(''):'<p>Здесь скоро появятся чемпионы!</p>')}openModal()}
function tone(freq,dur){if(!sound||sfxVolume<=0)return;try{let a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.055*sfxVolume,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}
function startMusic(){let audio=$('#bgMusic');audio.volume=musicVolume;if(musicOn)audio.play().catch(()=>{});else audio.pause();$('#soundBtn').textContent=musicOn?'♫':'♩'}
$('#musicVolume').value=Math.round(musicVolume*100);$('#sfxVolume').value=Math.round(sfxVolume*100);$('#musicVolume').oninput=e=>{musicVolume=+e.target.value/100;localStorage.setItem('mmMusicVolume',e.target.value);$('#bgMusic').volume=musicVolume};$('#sfxVolume').oninput=e=>{sfxVolume=+e.target.value/100;sound=sfxVolume>0;localStorage.setItem('mmSfxVolume',e.target.value)};
$('#startBtn').onclick=start;$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal'&&!locked)closeModal()};$$('[data-modal]').forEach(b=>b.onclick=()=>showInfo(b.dataset.modal));$('#exitBtn').onclick=()=>{clearInterval(soloInterval);$('#soloTimer').hidden=true;showScreen('home');locked=true};$('#restartBtn').onclick=start;$('#soundBtn').onclick=e=>{musicOn=!musicOn;localStorage.setItem('mmMusicOn',musicOn);startMusic();e.currentTarget.textContent=musicOn?'♫':'♩'};
